"""Regional and field-wide significance diagnostics for climate trends."""
from __future__ import annotations

import numpy as np
import xarray as xr

from ..spatial.weights import area_weighted_mean
from .seasonal import fdr_mask
from .trend import modified_mann_kendall, sens_slope, _mk_stats


def regional_mean(
    data: xr.DataArray,
    lat_dim: str = "latitude",
    lon_dim: str = "longitude",
    weights: xr.DataArray | None = None,
) -> xr.DataArray:
    """Return an area-weighted regional mean time series.

    For regular geographic grids, cosine-latitude weights are used when
    ``weights`` is not supplied. Exact cell-area weights may be supplied for
    irregular or curvilinear grids.
    """
    if lat_dim not in data.dims or lon_dim not in data.dims:
        raise ValueError(f"data must contain {lat_dim!r} and {lon_dim!r} dimensions")
    if weights is None:
        return area_weighted_mean(data, lat_dim=lat_dim, spatial_dims=(lat_dim, lon_dim))
    if not set((lat_dim, lon_dim)).issubset(weights.dims):
        raise ValueError("weights must span the requested latitude and longitude dimensions")
    return data.weighted(weights).mean(dim=(lat_dim, lon_dim), skipna=True)


def regional_trend(
    data: xr.DataArray,
    time_dim: str = "time",
    lat_dim: str = "latitude",
    lon_dim: str = "longitude",
    alpha: float = 0.05,
    weights: xr.DataArray | None = None,
    max_lag: int | None = None,
) -> xr.Dataset:
    """Calculate an autocorrelation-aware trend for an area-weighted region."""
    if not 0 < alpha < 1:
        raise ValueError("alpha must be between 0 and 1")
    series = regional_mean(data, lat_dim=lat_dim, lon_dim=lon_dim, weights=weights)
    result = modified_mann_kendall(series, dim=time_dim, max_lag=max_lag)
    result["sen_slope"] = sens_slope(series, dim=time_dim)
    result["significant"] = result["pvalue"] < alpha
    result.attrs.update(
        {
            "alpha": alpha,
            "weighting": "user-supplied cell areas" if weights is not None else "cosine latitude",
        }
    )
    return result


def _block_indices(n: int, block_length: int, rng: np.random.Generator) -> np.ndarray:
    """Generate a moving-block bootstrap index sequence of length ``n``."""
    if block_length < 1 or block_length > n:
        raise ValueError("block_length must be between 1 and the number of time steps")
    starts = rng.integers(0, n - block_length + 1, size=int(np.ceil(n / block_length)))
    return np.concatenate([np.arange(s, s + block_length) for s in starts])[:n]


def field_significance(
    data: xr.DataArray,
    dim: str = "time",
    alpha: float = 0.05,
    block_length: int = 5,
    n_resamples: int = 500,
    random_state: int | None = 0,
    detrend: bool = True,
) -> xr.Dataset:
    """Assess field-wide trend significance with a moving-block null.

    The field-wide statistic is the number of locally significant classical
    Mann-Kendall tests in the complete grid cells. The null is generated by
    moving-block resampling of detrended residual fields. A common set of time
    indices is applied to every grid cell, preserving the spatial covariance
    structure represented by the sampled field while the blocks preserve
    short-range temporal dependence.

    This is a field-significance diagnostic, not a replacement for local
    autocorrelation correction or FDR. Local results are reported separately
    using the package's modified Mann-Kendall test and Benjamini-Hochberg FDR.
    """
    if dim not in data.dims:
        raise ValueError(f"Dimension {dim!r} is not present in the input data")
    if not 0 < alpha < 1:
        raise ValueError("alpha must be between 0 and 1")
    if n_resamples < 1:
        raise ValueError("n_resamples must be at least 1")

    other_dims = tuple(d for d in data.dims if d != dim)
    if not other_dims:
        raise ValueError("field_significance requires at least one spatial dimension")

    series = data.transpose(dim, *other_dims)
    values = np.asarray(series.values, dtype=float)
    n = values.shape[0]
    flat = values.reshape(n, -1)

    # A common resampled time index requires complete cells. Incomplete cells
    # can still receive local p-values, but they are excluded from the
    # field-wide count so the observed and null statistics use the same cells.
    valid = np.isfinite(flat).all(axis=0)
    if not valid.any():
        raise ValueError("no complete grid cells are available for field significance")

    local = modified_mann_kendall(series, dim=dim)
    pvalue = local["pvalue"]
    pflat = np.asarray(pvalue.values).reshape(-1)
    observed_mask = valid & np.isfinite(pflat) & (pflat < alpha)
    observed_count = int(observed_mask.sum())
    n_cells = int(valid.sum())

    residual = flat[:, valid].copy()
    if detrend:
        slopes = np.asarray(sens_slope(series, dim=dim).values).reshape(-1)[valid]
        t = np.arange(n, dtype=float)[:, None]
        residual = residual - t * slopes[None, :]
        # Remove the robust location offset as well. The offset does not
        # affect MK, but centering makes the bootstrap null easier to inspect.
        residual = residual - np.nanmedian(residual, axis=0, keepdims=True)

    rng = np.random.default_rng(random_state)
    null_counts = np.empty(n_resamples, dtype=int)
    for i in range(n_resamples):
        idx = _block_indices(n, block_length, rng)
        sample = residual[idx, :]
        count = 0
        for j in range(n_cells):
            _, _, p, _ = _mk_stats(sample[:, j])
            if np.isfinite(p) and p < alpha:
                count += 1
        null_counts[i] = count

    field_p = (1.0 + np.count_nonzero(null_counts >= observed_count)) / (n_resamples + 1.0)
    critical_count = int(np.quantile(null_counts, 1.0 - alpha, method="higher"))

    result = xr.Dataset(
        {
            "pvalue": pvalue,
            "significant": pvalue < alpha,
            "significant_fdr": fdr_mask(pvalue, alpha=alpha),
            "observed_count": xr.DataArray(observed_count),
            "n_cells": xr.DataArray(n_cells),
            "critical_count": xr.DataArray(critical_count),
            "field_pvalue": xr.DataArray(field_p),
            "null_counts": xr.DataArray(null_counts, dims=("resample",)),
        }
    )
    result.attrs.update(
        {
            "method": "moving-block bootstrap of detrended residual fields",
            "block_length": block_length,
            "n_resamples": n_resamples,
            "alpha": alpha,
            "random_state": random_state,
            "complete_cells_only": True,
            "spatial_dependence": "preserved through common resampled time indices",
            "local_test": "modified Mann-Kendall",
            "bootstrap_count_test": "classical Mann-Kendall",
        }
    )
    return result


__all__ = ["regional_mean", "regional_trend", "field_significance"]
